apiVersion: batch/v1
kind: Job
metadata:
  name: syslogpars
spec:
  completions: 5
  parallelism: 10
  template:
    spec:
      containers:
      - name: syslogpars
        image: ./syslogpars
      restartPolicy: Never
  backoffLimit: 4